version: '3'

tasks:
  default:
    desc: Run the default task
    cmds:
      - task build
      - task test
      - task format
  build:
    desc: Build the project
    cmds:
      - mkdir -p bin
      - go build -o bin/clone-alive main.go

  test:
    desc: Run tests for the project
    cmds:
      - go test ./...

  format:
    desc: Format the codebase
    cmds:
      - gofmt -w .
      - goimports -w .
